builtins = [
    "__neg__",
    "__not__",
    "__add__",
    "__sub__",
    "__mul__",
    "__div__",
    "__mod__",
    "__pow__",
    "__and__",
    "__or__",
    "__eq__",
    "__neq__",
    "__lt__",
    "__gt__",
    "__leq__",
    "__geq__",
    "__pair__",
]
